Remove the matrix cleaner for testing + Fix image name

diff --git a/.github/workflows/entrypoint_pull_request.yml b/.github/workflows/entrypoint_pull_request.yml
--- a/.github/workflows/entrypoint_pull_request.yml
+++ b/.github/workflows/entrypoint_pull_request.yml
@@ -19,6 +19,7 @@ concurrency:
 
 env:
   # intermediary registry in which architecture-specific images must be pushed
+  BASE_IMAGE_NAME: "exegol-base"
   DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"
   # final registry target, in which arch-specific images must be aggregated
   DOCKER_TARGET_REPO: "nwodtuhs/exegol"
@@ -58,7 +59,9 @@ jobs:
         #arch: [arm64, amd64]
     uses: ./.github/workflows/sub_build_belt.yml
     with:
-      DOCKER_BUILD_REPO: ${{ needs.varset.outputs.DOCKER_BUILD_REPO }}
+      # BASE_IMAGE_NAME: ${{ needs.varset.outputs.BASE_IMAGE_NAME }}
+      DOCKER_BUILD_REPO: exegol-base
+      #DOCKER_BUILD_REPO: ${{ needs.varset.outputs.DOCKER_BUILD_REPO }}
       DOCKER_TARGET_REPO: ${{ needs.varset.outputs.DOCKER_TARGET_REPO }}
       IMAGE_BASE_NAME: ${{ needs.varset.outputs.IMAGE_BASE_NAME }}
       DOCKERFILE: ./build/base.dockerfile
@@ -76,7 +79,8 @@ jobs:
         #arch: [ arm64, amd64 ]
     uses: ./.github/workflows/sub_build_belt.yml
     with:
-      DOCKER_BUILD_REPO: ${{ needs.varset.outputs.DOCKER_BUILD_REPO }}
+      DOCKER_BUILD_REPO: exegol-misc
+      #DOCKER_BUILD_REPO: ${{ needs.varset.outputs.DOCKER_BUILD_REPO }}
       DOCKER_TARGET_REPO: ${{ needs.varset.outputs.DOCKER_TARGET_REPO }}
       IMAGE_BASE_NAME: ${{ needs.varset.outputs.IMAGE_BASE_NAME }}
       DOCKERFILE: ./build/misc.dockerfile
@@ -94,7 +98,8 @@ jobs:
         #arch: [ arm64, amd64 ]
     uses: ./.github/workflows/sub_build_belt.yml
     with:
-      DOCKER_BUILD_REPO: ${{ needs.varset.outputs.DOCKER_BUILD_REPO }}
+      DOCKER_BUILD_REPO: exegol-final
+      #DOCKER_BUILD_REPO: ${{ needs.varset.outputs.DOCKER_BUILD_REPO }}
       DOCKER_TARGET_REPO: ${{ needs.varset.outputs.DOCKER_TARGET_REPO }}
       IMAGE_BASE_NAME: ${{ needs.varset.outputs.IMAGE_BASE_NAME }}
       DOCKERFILE: ./build/final.dockerfile
@@ -102,25 +107,25 @@ jobs:
       ARCH: ${{ matrix.arch }}
       PR_MODE: true
 
-  clean_runners:
-    name: Clean runners
-    needs:
-      - varset
-      - build_belt
-    if: always() && !contains(needs.build_belt.outputs.build, 'failure')
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [ arm64 ]
-        #arch: [ arm64, amd64 ]
-    runs-on:
-      - self-hosted
-      - builder
-      - ${{ matrix.arch }}
-    steps:
-      - name: Remove built image ${{ needs.varset.outputs.IMAGE_BASE_NAME }}-${{ matrix.arch }}
-        run: |
-          image_name=${DOCKER_BUILD_REPO}:${{ needs.varset.outputs.IMAGE_BASE_NAME }}-${{ matrix.arch }}
-          echo "Removing $image_name"
-          docker image inspect $image_name || exit 0 && docker rmi $image_name
+  # clean_runners:
+  #   name: Clean runners
+  #   needs:
+  #     - varset
+  #     - image_belt
+  #   if: always() && !contains(needs.image_belt.outputs.build, 'failure')
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch: [ arm64 ]
+  #       #arch: [ arm64, amd64 ]
+  #   runs-on:
+  #     - self-hosted
+  #     - builder
+  #     - ${{ matrix.arch }}
+  #   steps:
+  #     - name: Remove built image ${{ needs.varset.outputs.IMAGE_BASE_NAME }}-${{ matrix.arch }}
+  #       run: |
+  #         image_name=${DOCKER_BUILD_REPO}:${{ needs.varset.outputs.IMAGE_BASE_NAME }}-${{ matrix.arch }}
+  #         echo "Removing $image_name"
+  #         docker image inspect $image_name || exit 0 && docker rmi $image_name
 
